### ISSUE TITLE
Is this for Clover POS and compatible with all clover products? 

### ISSUE THREAD

**Issue by losh11** [qimingfang/react-native-clover-example#1]
A README would be nice, I guess...

**Comment by dk0r** [comment]
> A README would be nice, I guess...

Got here searching for the same thing (a react-native Clover PointOfSale component lib)

**Comment by morenoh149** [comment]
Reviewing the code it does seem to be a minimal example of a react native app using the clover-android-sdk.

This native module here exposes a `show` method https://github.com/qimingfang/react-native-clover-example/blob/master/android/app/src/main/java/com/unifi/CloverPackage.java

and here it is imported into js https://github.com/qimingfang/react-native-clover-example/blob/master/app/index.js#L15

We'd want to make a new repo for just the native module and provide instructions for how to add it to a vanilla react native app.
